/**
 * NHỊ THẬP BÁT TÚ (28 SAO THIÊN VĂN CỔ ĐIỂN)
 * Chu kỳ 28 ngày tính theo chuẩn Julian Day Number.
 * 4 Nhóm Linh Thú: Thanh Long (Đông), Huyền Vũ (Bắc), Bạch Hổ (Tây), Chu Tước (Nam).
 */

export const NHI_THAP_BAT_TU = [
  {
    name: 'Giác',
    fullName: 'Giác Mộc Giao',
    animal: 'Giao long',
    element: 'Mộc',
    direction: 'Đông Phương Thanh Long',
    isGood: true,
    rating: 'Cát Tinh',
    poem: 'Giác tinh tọa chiếu tự vinh xương / Vạn sự khởi công đắc cát tường / Hưng công giá thú tăng tài lộc / Phú quý vinh hoa thế thế trường.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Nhập học', 'Cầu danh vọng', 'Ký kết hợp đồng'],
    badFor: ['Chôn cất', 'Xây dựng mồ mả'],
  },
  {
    name: 'Cang',
    fullName: 'Cang Kim Long',
    animal: 'Rồng',
    element: 'Kim',
    direction: 'Đông Phương Thanh Long',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Cang tinh tác sự hữu tai ương / Bất nghi giá thú kiến tài thương / Mai táng nhược hoàn phùng thử nhật / Đương môn tiểu tử thụ tai ương.',
    goodFor: ['Tế tự cầu an', 'Cắt tóc', 'Trừ tà'],
    badFor: ['Cưới hỏi', 'Xây nhà', 'Khai trương', 'Chôn cất'],
  },
  {
    name: 'Đê',
    fullName: 'Đê Thổ Lạc',
    animal: 'Lạc đà',
    element: 'Thổ',
    direction: 'Đông Phương Thanh Long',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Đê tinh tạo tác sự giai nan / Phí tận tâm cơ thực bất an / Khởi công tác sự đa trắc trở / Phòng gia đạo nghịch hữu tai loan.',
    goodFor: ['Sửa chữa nhỏ', 'Bắt trộm', 'Gieo trồng'],
    badFor: ['Động thổ', 'Cưới hỏi', 'Khai trương', 'Đi xa'],
  },
  {
    name: 'Phòng',
    fullName: 'Phòng Nhật Thố',
    animal: 'Thỏ',
    element: 'Nhật',
    direction: 'Đông Phương Thanh Long',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Phòng tinh chiếu diệu khởi cao môn / Phú quý tài nguyên tụ nhất môn / Cưới hỏi xuất hành giai đắc lợi / Gia đạo hưng long tử tôn vinh.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Động thổ', 'Xuất hành', 'Cầu tài lộc', 'Mua nhà đất'],
    badFor: ['Kiện tụng tranh chấp'],
  },
  {
    name: 'Tâm',
    fullName: 'Tâm Nguyệt Hồ',
    animal: 'Cáo',
    element: 'Nguyệt',
    direction: 'Đông Phương Thanh Long',
    isGood: false,
    rating: 'Đại Hung Tinh',
    poem: 'Tâm tinh bất khả khởi lâu đài / Đương nhật thi vi chủ họa tai / Giá thú nhập trạch đa bất lợi / Phong ba trắc trở sự nan khai.',
    goodFor: ['Trừ khử kẻ xấu', 'Dọn dẹp', 'Tiêu hủy phế tích'],
    badFor: ['Cưới hỏi', 'Làm nhà', 'Khai trương', 'Ký kết'],
  },
  {
    name: 'Vĩ',
    fullName: 'Vĩ Hỏa Hổ',
    animal: 'Hổ',
    element: 'Hỏa',
    direction: 'Đông Phương Thanh Long',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Vĩ tinh tạo tác đắc thiên ân / Phú quý vinh hoa mãn môn đình / Chiêu tài tiến bảo khai hoa kết / Nhân đinh hưng vượng phước thần tinh.',
    goodFor: ['Khai trương', 'Động thổ', 'Cưới hỏi', 'Nhập trạch', 'Cầu tài', 'Giao dịch lớn'],
    badFor: ['Đào giếng', 'Đi thuyền'],
  },
  {
    name: 'Cơ',
    fullName: 'Cơ Thủy Báo',
    animal: 'Báo',
    element: 'Thủy',
    direction: 'Đông Phương Thanh Long',
    isGood: true,
    rating: 'Cát Tinh',
    poem: 'Cơ tinh tạo tác sự vinh hoa / Tật bệnh tiêu trừ phúc mãn gia / Mở cửa thông thương sinh lợi tức / Gia đình hòa thuận nở nghìn hoa.',
    goodFor: ['Khai trương', 'Cầu tài', 'Xuất hành', 'Chữa bệnh', 'Mua sắm tích lũy'],
    badFor: ['Chôn cất'],
  },
  {
    name: 'Đẩu',
    fullName: 'Đẩu Mộc Giải',
    animal: 'Cua biển',
    element: 'Mộc',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: true,
    rating: 'Cát Tinh',
    poem: 'Đẩu tinh tạo tác sự khả nghi / Điền trạch sung doanh tiến ích thì / Tài lộc tăng trường nhân sự hảo / Cử đầu nghênh tiếp phúc thùy thùy.',
    goodFor: ['Xây dựng', 'Động thổ', 'Khai trương', 'Cưới hỏi', 'Mua xe', 'Ký kết'],
    badFor: ['Đi thuyền sông nước'],
  },
  {
    name: 'Ngưu',
    fullName: 'Ngưu Kim Ngưu',
    animal: 'Trâu',
    element: 'Kim',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: false,
    rating: 'Đại Hung Tinh',
    poem: 'Ngưu tinh tạo tác sự bất an / Điền súc tiêu hao hữu tổn hoàn / Giá thú khởi công vô lợi ích / Phòng sinh trắc trở biến cố lan.',
    goodFor: ['Chăn nuôi', 'Cày bừa gieo cấy'],
    badFor: ['Cưới hỏi', 'Làm nhà', 'Khai trương', 'Xuất hành'],
  },
  {
    name: 'Nữ',
    fullName: 'Nữ Thổ Bức',
    animal: 'Dơi',
    element: 'Thổ',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Nữ tinh chiếu lâm chủ phá hao / Tranh đoạt thị phi dạ bất yên / Bất khả khởi công cầu sự nghiệp / Dĩ hòa vi quý thủ bình an.',
    goodFor: ['May vá', 'Nghỉ ngơi', 'Làm việc thiện'],
    badFor: ['Cưới hỏi', 'Khởi nghiệp', 'Tranh tụng'],
  },
  {
    name: 'Hư',
    fullName: 'Hư Nhật Thử',
    animal: 'Chuột',
    element: 'Nhật',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: false,
    rating: 'Đại Hung Tinh',
    poem: 'Hư tinh tạo tác sự hư vô / Gia tài hao hụt sự nan đồ / Khởi công xuất hành giai kỵ túc / Tu phòng đạo tặc lộng huyền hư.',
    goodFor: ['Tế tự cầu bình an'],
    badFor: ['Mọi việc đại sự: cưới hỏi, động thổ, khai trương'],
  },
  {
    name: 'Nguy',
    fullName: 'Nguy Nguyệt Yến',
    animal: 'Chim én',
    element: 'Nguyệt',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Nguy tinh cao chiếu hiểm nguy đa / Tạo tác kinh doanh tổn thất hoa / An phận thủ thường tri túc lạc / Xuất hành cẩn trọng hiểm phong ba.',
    goodFor: ['Sửa chữa gia cố hàng rào', 'Phòng thủ'],
    badFor: ['Đi xa', 'Khai trương', 'Cưới hỏi', 'Động thổ'],
  },
  {
    name: 'Thất',
    fullName: 'Thất Hỏa Trư',
    animal: 'Heo',
    element: 'Hỏa',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Thất tinh chiếu diệu sự tương thông / Vinh hiển vinh hoa ngộ quý nhân / Phú quý tài phong tề tụ lại / Cát tinh cao chiếu khởi gia môn.',
    goodFor: ['Động thổ', 'Cưới hỏi', 'Khai trương', 'Nhập trạch', 'Ký hợp đồng', 'Xuất hành'],
    badFor: ['Chôn cất'],
  },
  {
    name: 'Bích',
    fullName: 'Bích Thủy Du',
    animal: 'Rái cá',
    element: 'Thủy',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Bích tinh tạo tác vượng gia đình / Hưng long điền trạch phát tài kinh / Cưới gả sinh con đa phú quý / Sự nghiệp thanh vân vạn tải trường.',
    goodFor: ['Cưới hỏi', 'Động thổ', 'Khai trương', 'Nhập trạch', 'Cầu tài', 'Thi cử'],
    badFor: ['Tranh chấp kiện cáo'],
  },
  {
    name: 'Khuê',
    fullName: 'Khuê Mộc Lang',
    animal: 'Sói',
    element: 'Mộc',
    direction: 'Tây Phương Bạch Hổ',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Khuê tinh bất khả khởi môn tường / Khởi công tác sự hữu tai ương / Tài vật tiêu hao gia đạo loạn / Thủ kỷ an bần miễn họa thương.',
    goodFor: ['Học tập', 'Đọc sách', 'Làm thơ', 'Nghiên cứu văn chương'],
    badFor: ['Động thổ', 'Khai trương', 'Cưới hỏi', 'Đào móng'],
  },
  {
    name: 'Lâu',
    fullName: 'Lâu Kim Cẩu',
    animal: 'Chó',
    element: 'Kim',
    direction: 'Tây Phương Bạch Hổ',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Lâu tinh tác sự đại hưng long / Điền sản phong doanh vượng tử tôn / Quý nhân đắc lộ khai thông mạch / Vạn sự trình tường phúc tự hưng.',
    goodFor: ['Động thổ', 'Làm nhà', 'Cưới hỏi', 'Khai trương', 'Gieo trồng', 'Mua đất'],
    badFor: ['Chữa mắt'],
  },
  {
    name: 'Vị',
    fullName: 'Vị Thổ Trĩ',
    animal: 'Chim trĩ',
    element: 'Thổ',
    direction: 'Tây Phương Bạch Hổ',
    isGood: true,
    rating: 'Cát Tinh',
    poem: 'Vị tinh cao chiếu phúc lâm môn / Tài nguyên quảng tấn tích kim ngân / Mưu sự khởi công giai thuận toại / Gia đạo an khang bảo thái bình.',
    goodFor: ['Khai trương', 'Cưới hỏi', 'Mua sắm', 'Động thổ', 'Xuất hành'],
    badFor: ['Chôn cất'],
  },
  {
    name: 'Mão',
    fullName: 'Mão Nhật Kê',
    animal: 'Gà',
    element: 'Nhật',
    direction: 'Tây Phương Bạch Hổ',
    isGood: false,
    rating: 'Đại Hung Tinh',
    poem: 'Mão tinh tạo tác sự đa ưu / Phí tổn tiền tài họa chẳng ngừng / Bất khả hôn nhân khai bảo khố / Thận trọng phòng thân giữ lấy mình.',
    goodFor: ['Tế tự cầu an', 'Cắt tóc'],
    badFor: ['Cưới hỏi', 'Khai trương', 'Làm nhà', 'Ký hợp đồng'],
  },
  {
    name: 'Tất',
    fullName: 'Tất Nguyệt Ô',
    animal: 'Quạ',
    element: 'Nguyệt',
    direction: 'Tây Phương Bạch Hổ',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Tất tinh chiếu diệu sự thông hanh / Hưng công giá thú tiến quan thanh / Hỷ khí doanh môn chiêu phúc lộc / Sinh ý hưng long sự sự thành.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Động thổ', 'Nhập trạch', 'Ký kết', 'Xuất hành'],
    badFor: ['Chôn cất'],
  },
  {
    name: 'Chủy',
    fullName: 'Chủy Hỏa Hầu',
    animal: 'Khỉ',
    element: 'Hỏa',
    direction: 'Tây Phương Bạch Hổ',
    isGood: false,
    rating: 'Đại Hung Tinh',
    poem: 'Chủy tinh bất khả khởi môn đình / Thừa tướng triều ban dã giáng tinh / Khởi công tác sự vô thu hoạch / Đề phòng trộm cướp dữ tai kinh.',
    goodFor: ['Chặt cây', 'San nền'],
    badFor: ['Mọi việc khởi sự: cưới hỏi, động thổ, khai trương'],
  },
  {
    name: 'Sâm',
    fullName: 'Sâm Thủy Viên',
    animal: 'Vượn',
    element: 'Thủy',
    direction: 'Tây Phương Bạch Hổ',
    isGood: true,
    rating: 'Cát Tinh',
    poem: 'Sâm tinh chiếu chiếu cát tường khai / Mở cửa cầu tài phát thịnh tài / Gia đạo hòa hài sinh quý tử / Danh vọng cao thăng vạn dặm dài.',
    goodFor: ['Khai trương', 'Cầu tài', 'Cưới hỏi', 'Xuất hành', 'Ký kết'],
    badFor: ['Chôn cất'],
  },
  {
    name: 'Tỉnh',
    fullName: 'Tỉnh Mộc Hãn',
    animal: 'Chó sói vằn',
    element: 'Mộc',
    direction: 'Nam Phương Chu Tước',
    isGood: true,
    rating: 'Cát Tinh',
    poem: 'Tỉnh tinh tạo tác đại phong doanh / Nông vụ điền trang đắc bội thu / Thi cử đỗ cao danh vọng hiển / Gia hòa vạn sự hưng long hưu.',
    goodFor: ['Động thổ', 'Khai trương', 'Học hành thi cử', 'Trồng trọt'],
    badFor: ['Cưới hỏi', 'Chôn cất'],
  },
  {
    name: 'Quỷ',
    fullName: 'Quỷ Kim Dương',
    animal: 'Dê',
    element: 'Kim',
    direction: 'Nam Phương Chu Tước',
    isGood: false,
    rating: 'Đại Hung Tinh',
    poem: 'Quỷ tinh chiếu lâm sự đa sầu / Tật bệnh quan phi họa khởi đầu / Bất nghi kết hôn sinh sự loạn / Thận trọng giữ gìn phúc mới lưu.',
    goodFor: ['Tế tự trừ tà', 'Chữa bệnh'],
    badFor: ['Cưới hỏi', 'Làm nhà', 'Khai trương', 'Xuất hành'],
  },
  {
    name: 'Liễu',
    fullName: 'Liễu Thổ Chương',
    animal: 'Nai',
    element: 'Thổ',
    direction: 'Nam Phương Chu Tước',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Liễu tinh tạo tác sự vô thường / Đề phòng hao tài dữ thị phi / An phận thủ thường tri túc tiệp / Mưu sự đại đồ khởi chẳng quy.',
    goodFor: ['Dọn dẹp phế thải'],
    badFor: ['Cưới hỏi', 'Động thổ', 'Khai trương', 'Đi xa'],
  },
  {
    name: 'Tinh',
    fullName: 'Tinh Nhật Mã',
    animal: 'Ngựa',
    element: 'Nhật',
    direction: 'Nam Phương Chu Tước',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Tinh tinh cao chiếu sự nan thành / Gia tài tiêu tán họa liên miên / Bất nghi tạo tác đồ sinh sự / An định tâm linh thủ đạo yên.',
    goodFor: ['Xây tường rào', 'Chữa bệnh'],
    badFor: ['Cưới hỏi', 'Động thổ', 'Làm nhà mới'],
  },
  {
    name: 'Trương',
    fullName: 'Trương Nguyệt Lộc',
    animal: 'Hươu',
    element: 'Nguyệt',
    direction: 'Nam Phương Chu Tước',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Trương tinh chiếu sáng rực tiền đồ / Giá thú khai hoa kết trái ngô / Động thổ hưng công thêm phúc lộc / Kim ngân tài bảo nhập vào kho.',
    goodFor: ['Cưới hỏi', 'Động thổ', 'Khai trương', 'Nhập trạch', 'Ký hợp đồng', 'Mua xe'],
    badFor: ['Chôn cất'],
  },
  {
    name: 'Dực',
    fullName: 'Dực Hỏa Xà',
    animal: 'Rắn',
    element: 'Hỏa',
    direction: 'Nam Phương Chu Tước',
    isGood: true,
    rating: 'Cát Tinh',
    poem: 'Dực tinh tạo tác đại cát xương / Cưới gả sinh tài phúc thọ trường / Mở cửa cầu vinh nhân ý toại / Vinh hoa phú quý đắc phi thường.',
    goodFor: ['Cưới hỏi', 'Xuất hành', 'Khai trương', 'Cầu tài', 'Nhậm chức'],
    badFor: ['Chôn cất'],
  },
  {
    name: 'Chẩn',
    fullName: 'Chẩn Thủy Dẫn',
    animal: 'Giun đất',
    element: 'Thủy',
    direction: 'Nam Phương Chu Tước',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Chẩn tinh chiếu diệu đại hưng gia / Thăng quan tiến chức phúc đầy nhà / Cưới gả mua bán giai đắc lợi / Tử tôn hiếu thảo nở ngàn hoa.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Động thổ', 'Xuất hành', 'Cầu tài', 'Ký kết'],
    badFor: ['Chôn cất'],
  },
];

/**
 * Tính Sao trong Nhị Thập Bát Tú của ngày theo Julian Day Number
 * Chu kỳ 28 ngày cố định
 */
export function getDayNhiThapBatTu(jd) {
  // Chu kỳ chuẩn sao theo Julian Day:
  // (jd + 17) % 28 đảm bảo ngày Chủ Nhật luôn ứng với 4 sao Nhật (Phòng, Hư, Mão, Tinh)
  // và Thứ Năm ứng với 4 sao Mộc (Giác, Đẩu, Khuê, Tỉnh).
  const starIndex = (jd + 17) % 28;
  const star = NHI_THAP_BAT_TU[starIndex];
  return {
    starIndex,
    name: star.name,
    fullName: star.fullName,
    animal: star.animal,
    element: star.element,
    direction: star.direction,
    isGood: star.isGood,
    rating: star.rating,
    poem: star.poem,
    goodFor: star.goodFor,
    badFor: star.badFor,
  };
}
