/**
 * NHỊ THẬP BÁT TÚ (28 VÌ SAO THIÊN VĂN CỔ ĐIỂN)
 * Phân chia theo Tứ Tượng (Thanh Long, Huyền Vũ, Bạch Hổ, Chu Tước).
 * Chu kỳ 28 ngày phối hợp Thất Diệu (Nhật, Nguyệt, Hỏa, Thủy, Mộc, Kim, Thổ).
 * Chuẩn hóa độ chính xác tuyệt đối theo Julian Day Number: (jd + 11) % 28.
 */

export const NHI_THAP_BAT_TU = [
  {
    name: 'Giác',
    fullName: 'Giác Mộc Giao',
    animal: 'Giao long',
    element: 'Mộc',
    weekday: 'Thứ Năm',
    direction: 'Đông Phương Thanh Long',
    isGood: true,
    rating: 'Cát Tinh',
    poem: 'Giác tinh tọa chiếu tự vinh xương / Vạn sự khởi công đắc cát tường / Hưng công giá thú tăng tài lộc / Phú quý vinh hoa thế thế trường.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Nhập học', 'Cầu danh vọng', 'Ký kết hợp đồng'],
    badFor: ['Chôn cất', 'Xây dựng mồ mả'],
  },
  {
    name: 'Cang',
    fullName: 'Cang Kim Long',
    animal: 'Rồng',
    element: 'Kim',
    weekday: 'Thứ Sáu',
    direction: 'Đông Phương Thanh Long',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Cang tinh tác sự hữu tai ương / Bất nghi giá thú kiến tài thương / Mai táng nhược hoàn phùng thử nhật / Đương môn tiểu tử thụ tai ương.',
    goodFor: ['Tế tự cầu an', 'Cắt tóc', 'Trừ tà'],
    badFor: ['Cưới hỏi', 'Xây nhà', 'Khai trương', 'Chôn cất'],
  },
  {
    name: 'Đê',
    fullName: 'Đê Thổ Lạc',
    animal: 'Lạc đà',
    element: 'Thổ',
    weekday: 'Thứ Bảy',
    direction: 'Đông Phương Thanh Long',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Đê tinh tạo tác sự giai nan / Phí tận tâm cơ thực bất an / Khởi công tác sự đa trắc trở / Phòng gia đạo nghịch hữu tai loan.',
    goodFor: ['Sửa chữa nhỏ', 'Bắt trộm', 'Gieo trồng'],
    badFor: ['Động thổ', 'Cưới hỏi', 'Khai trương', 'Đi xa'],
  },
  {
    name: 'Phòng',
    fullName: 'Phòng Nhật Thố',
    animal: 'Thỏ',
    element: 'Nhật',
    weekday: 'Chủ Nhật',
    direction: 'Đông Phương Thanh Long',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Phòng tinh chiếu diệu khởi cao môn / Phú quý tài nguyên tụ nhất môn / Cưới hỏi xuất hành giai đắc lợi / Gia đạo hưng long tử tôn vinh.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Động thổ', 'Xuất hành', 'Cầu tài lộc', 'Mua nhà đất'],
    badFor: ['Kiện tụng tranh chấp'],
  },
  {
    name: 'Tâm',
    fullName: 'Tâm Nguyệt Hồ',
    animal: 'Cáo',
    element: 'Nguyệt',
    weekday: 'Thứ Hai',
    direction: 'Đông Phương Thanh Long',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Tâm tinh tạo tác tổn phong cương / Khởi tạo hưng công bất cát tường / Giá thú tài nguyên tiêu tán tận / Mai táng hoàn ngộ đại tai ương.',
    goodFor: ['Cúng bái', 'Làm việc thiện'],
    badFor: ['Cưới hỏi', 'Khai trương', 'Làm nhà', 'Ký hợp đồng'],
  },
  {
    name: 'Vĩ',
    fullName: 'Vĩ Hỏa Hổ',
    animal: 'Hổ',
    element: 'Hỏa',
    weekday: 'Thứ Ba',
    direction: 'Đông Phương Thanh Long',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Vĩ tinh tạo tác đắc thiên ân / Phú quý vinh hoa nhập thị môn / Chiêu tài tiến bảo khai hoa chúc / Đinh tài lưỡng vượng thế gia xuân.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Động thổ', 'Xuất hành', 'Nhập trạch', 'Lắp đặt bàn thờ'],
    badFor: ['Đóng thuyền', 'Đi thuyền vượt biển'],
  },
  {
    name: 'Cơ',
    fullName: 'Cơ Thủy Báo',
    animal: 'Báo',
    element: 'Thủy',
    weekday: 'Thứ Tư',
    direction: 'Đông Phương Thanh Long',
    isGood: true,
    rating: 'Cát Tinh',
    poem: 'Cơ tinh tạo tác sự giai toàn / Tài lộc doanh môn thế đại truyền / Tu tạo khai môn thiêm phúc trạch / Gia đình hòa thuận lạc an nhiên.',
    goodFor: ['Khai trương', 'Động thổ', 'Trồng trọt', 'Cầu tài', 'Tu tạo nhà cửa'],
    badFor: ['Chôn cất'],
  },
  {
    name: 'Đẩu',
    fullName: 'Đẩu Mộc Giải',
    animal: 'Cua',
    element: 'Mộc',
    weekday: 'Thứ Năm',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: true,
    rating: 'Cát Tinh',
    poem: 'Đẩu tinh tạo tác sự giai thăng / Phúc lộc vinh hoa nhật nhật tăng / Giá thú hưng công sinh quý tử / Môn đình hưng thịnh thế tôn hưng.',
    goodFor: ['Cưới hỏi', 'Nhập trạch', 'Động thổ', 'Mua sắm', 'Khai trương'],
    badFor: ['Đi thuyền xa'],
  },
  {
    name: 'Ngưu',
    fullName: 'Ngưu Kim Ngưu',
    animal: 'Trâu',
    element: 'Kim',
    weekday: 'Thứ Sáu',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Ngưu tinh tạo tác bất khả thi / Họa hoạn đa đoan khởi thị phi / Cưới gả phân ly điền trạch thoái / Khởi công tác sự sự giai nguy.',
    goodFor: ['Làm việc thiện', 'Dọn cỏ cắt tỉa cảnh quan'],
    badFor: ['Cưới hỏi', 'Khai trương', 'Xây nhà', 'Ký hợp đồng'],
  },
  {
    name: 'Nữ',
    fullName: 'Nữ Thổ Bức',
    animal: 'Dơi',
    element: 'Thổ',
    weekday: 'Thứ Bảy',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Nữ tinh tạo tác khởi bi ai / Gia đạo bất hòa phá sản tài / Khởi công làm nhà phòng khẩu thiệt / Hôn nhân bất lợi tử tôn ai.',
    goodFor: ['Tế tự cầu an', 'Cắt may', 'Sửa chữa chuồng trại'],
    badFor: ['Cưới hỏi', 'Khai trương', 'Động thổ', 'Xuất hành'],
  },
  {
    name: 'Hư',
    fullName: 'Hư Nhật Thử',
    animal: 'Chuột',
    element: 'Nhật',
    weekday: 'Chủ Nhật',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Hư tinh tạo tác sự tao ương / Gia sản điền viên tổn hại thương / Cưới hỏi phân ly thân thích oán / Khởi công tác sự chủ hư không.',
    goodFor: ['Cúng bái trừ tà'],
    badFor: ['Cưới hỏi', 'Khai trương', 'Ký hợp đồng', 'Xây cất'],
  },
  {
    name: 'Nguy',
    fullName: 'Nguy Nguyệt Yến',
    animal: 'Chim én',
    element: 'Nguyệt',
    weekday: 'Thứ Hai',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Nguy tinh tạo tác hữu bi ưu / Tai ách quan phi sự chẳng lầu / Động thổ khai môn phòng tán thất / Khởi công mưu sự tổn công đầu.',
    goodFor: ['Chôn cất', 'Xây tường rào bao quanh'],
    badFor: ['Cưới hỏi', 'Làm nhà', 'Mở tiệm', 'Đi xa'],
  },
  {
    name: 'Thất',
    fullName: 'Thất Hỏa Trư',
    animal: 'Lợn',
    element: 'Hỏa',
    weekday: 'Thứ Ba',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Thất tinh tạo tác phúc lộc đa / Cưới hỏi giao tế đại hưng gia / Khởi công dựng cột thêm con thảo / Phú quý vinh hoa mãn ốc hoa.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Động thổ', 'Nhập trạch', 'Xuất hành', 'Cầu tài'],
    badFor: ['Chôn cất'],
  },
  {
    name: 'Bích',
    fullName: 'Bích Thủy Dư',
    animal: 'Rái cá',
    element: 'Thủy',
    weekday: 'Thứ Tư',
    direction: 'Bắc Phương Huyền Vũ',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Bích tinh tạo tác vạn sự toàn / Cưới gả khai trương tấn điền viên / Khởi công hưng tạo tăng quan lộc / Gia hòa hưng vượng thế truyền miên.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Động thổ', 'Nhập trạch', 'Ký hợp đồng', 'Xuất hành'],
    badFor: ['Tranh chấp khẩu thiệt'],
  },
  {
    name: 'Khuê',
    fullName: 'Khuê Mộc Lang',
    animal: 'Chó sói',
    element: 'Mộc',
    weekday: 'Thứ Năm',
    direction: 'Tây Phương Bạch Hổ',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Khuê tinh tạo tác sự nan thành / Gia đạo tiêu hao bệnh hoạn sinh / Cưới gả xuất hành đa trắc trở / Khởi công tác sự uổng tâm tình.',
    goodFor: ['Sửa tường rào', 'Đào mương dẫn nước'],
    badFor: ['Cưới hỏi', 'Khai trương', 'Làm nhà mới', 'Chôn cất'],
  },
  {
    name: 'Lâu',
    fullName: 'Lâu Kim Cẩu',
    animal: 'Chó',
    element: 'Kim',
    weekday: 'Thứ Sáu',
    direction: 'Tây Phương Bạch Hổ',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Lâu tinh chiếu diệu thế vô song / Điền địa trân châu mãn khố phong / Cưới gả khai môn sinh quý tử / Gia đình hưng vượng phúc trùng trùng.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Động thổ', 'Nhập trạch', 'Mua xe', 'Cầu tài'],
    badFor: ['Kiện tụng'],
  },
  {
    name: 'Vị',
    fullName: 'Vị Thổ Trĩ',
    animal: 'Chim trĩ',
    element: 'Thổ',
    weekday: 'Thứ Bảy',
    direction: 'Tây Phương Bạch Hổ',
    isGood: true,
    rating: 'Cát Tinh',
    poem: 'Vị tinh tạo tác sự hanh thông / Tài bảo tiến ích nhập môn đình / Cưới gả hưng công tăng phúc thọ / Phú quý vinh hoa hưởng thái bình.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Xuất hành', 'Động thổ', 'Lập bàn thờ'],
    badFor: ['Chôn cất'],
  },
  {
    name: 'Mão',
    fullName: 'Mão Nhật Kê',
    animal: 'Gà',
    element: 'Nhật',
    weekday: 'Chủ Nhật',
    direction: 'Tây Phương Bạch Hổ',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Mão tinh tạo tác hữu tai ương / Bất nghi giá thú tổn nhân thương / Động thổ tài nguyên tiêu tán tận / Phùng chi mưu sự sự nan tường.',
    goodFor: ['Xây tường bao', 'Bắt trộm', 'Diệt sâu bọ'],
    badFor: ['Cưới hỏi', 'Động thổ', 'Khai trương', 'Đi xa'],
  },
  {
    name: 'Tất',
    fullName: 'Tất Nguyệt Ô',
    animal: 'Quạ',
    element: 'Nguyệt',
    weekday: 'Thứ Hai',
    direction: 'Tây Phương Bạch Hổ',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Tất tinh tạo tác phúc lộc lai / Khai môn lập trạch tấn tiền tài / Hôn nhân giá thú sinh quý tử / Phú quý song toàn thọ khảo giai.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Động thổ', 'Đào giếng', 'Nhập trạch', 'Ký hợp đồng'],
    badFor: ['Tranh chấp kiện cáo'],
  },
  {
    name: 'Chủy',
    fullName: 'Chủy Hỏa Hầu',
    animal: 'Khỉ',
    element: 'Hỏa',
    weekday: 'Thứ Ba',
    direction: 'Tây Phương Bạch Hổ',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Chủy tinh tạo tác sự giai nguy / Họa hoạn tranh đoạt khởi thị phi / Cưới gả phân ly tài sản phá / Khởi công tác sự hận nan quy.',
    goodFor: ['Tế tự cầu an', 'Cắt tóc giải xui'],
    badFor: ['Cưới hỏi', 'Khai trương', 'Làm nhà', 'Mua xe'],
  },
  {
    name: 'Sâm',
    fullName: 'Sâm Thủy Viên',
    animal: 'Vượn',
    element: 'Thủy',
    weekday: 'Thứ Tư',
    direction: 'Tây Phương Bạch Hổ',
    isGood: true,
    rating: 'Cát Tinh',
    poem: 'Sâm tinh chiếu diệu khởi cao môn / Phú quý tài nguyên tụ nhất thôn / Cưới hỏi xuất hành giai hữu ích / Hưng gia vượng tộc vĩnh trường tồn.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Xuất hành', 'Cầu tài lộc', 'Nhập học'],
    badFor: ['Chôn cất'],
  },
  {
    name: 'Tỉnh',
    fullName: 'Tỉnh Mộc Hãn',
    animal: 'Chó sói hãn',
    element: 'Mộc',
    weekday: 'Thứ Năm',
    direction: 'Nam Phương Chu Tước',
    isGood: true,
    rating: 'Cát Tinh',
    poem: 'Tỉnh tinh tạo tác đại cát tường / Thi cử đăng khoa bảng tháp vàng / Khởi công giá thú sinh tài lộc / Phú quý vinh hoa phúc thế trường.',
    goodFor: ['Động thổ', 'Đào móng', 'Khai trương', 'Cưới hỏi', 'Ký hợp đồng'],
    badFor: ['Chôn cất'],
  },
  {
    name: 'Quỷ',
    fullName: 'Quỷ Kim Dương',
    animal: 'Dê',
    element: 'Kim',
    weekday: 'Thứ Sáu',
    direction: 'Nam Phương Chu Tước',
    isGood: false,
    rating: 'Đại Hung Tinh',
    poem: 'Quỷ tinh tạo tác tổn phong cương / Táng mai nhật phùng hữu bi thương / Cưới gả phân ly thân thích biệt / Khởi công mưu sự tổn tài ương.',
    goodFor: ['Cúng tế cầu siêu', 'Tẩy uế trừ tà'],
    badFor: ['Cưới hỏi', 'Động thổ', 'Khai trương', 'Làm nhà', 'Xuất hành'],
  },
  {
    name: 'Liễu',
    fullName: 'Liễu Thổ Chương',
    animal: 'Hươu xạ',
    element: 'Thổ',
    weekday: 'Thứ Bảy',
    direction: 'Nam Phương Chu Tước',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Liễu tinh tạo tác sự nan an / Khởi tạo hưng công tổn sự hoàn / Cưới gả phân ly thân bằng oán / Mai táng phùng chi tật bệnh thảm.',
    goodFor: ['Tế bái thần linh'],
    badFor: ['Cưới hỏi', 'Khai trương', 'Làm nhà', 'Chôn cất'],
  },
  {
    name: 'Tinh',
    fullName: 'Tinh Nhật Mã',
    animal: 'Ngựa',
    element: 'Nhật',
    weekday: 'Chủ Nhật',
    direction: 'Nam Phương Chu Tước',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Tinh tinh tạo tác hữu tai ương / Bất nghi giá thú tổn thân thương / Khởi công hưng tạo phòng khẩu thiệt / Mai táng phùng chi gia thất lương.',
    goodFor: ['Xây tường bao', 'Diệt trừ sâu bọ'],
    badFor: ['Cưới hỏi', 'Khai trương', 'Làm nhà'],
  },
  {
    name: 'Trương',
    fullName: 'Trương Nguyệt Lộc',
    animal: 'Nai',
    element: 'Nguyệt',
    weekday: 'Thứ Hai',
    direction: 'Nam Phương Chu Tước',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Trương tinh tạo tác tiến tiền tài / Khởi tạo khai trương vạn sự giai / Cưới gả thăng quan sinh quý tử / Môn đình hưng thịnh phúc như lai.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Động thổ', 'Nhập trạch', 'Ký hợp đồng', 'Xuất hành'],
    badFor: ['Chôn cất'],
  },
  {
    name: 'Dực',
    fullName: 'Dực Hỏa Xà',
    animal: 'Rắn',
    element: 'Hỏa',
    weekday: 'Thứ Ba',
    direction: 'Nam Phương Chu Tước',
    isGood: false,
    rating: 'Hung Tinh',
    poem: 'Dực tinh tạo tác tổn gia tài / Khởi tạo hưng công bất khả hoài / Cưới gả ly biệt đa hoạn nạn / Phùng chi mưu sự mộng trần ai.',
    goodFor: ['Cắt may', 'Sửa chữa dụng cụ gia đình'],
    badFor: ['Cưới hỏi', 'Khai trương', 'Làm nhà', 'Đi xa'],
  },
  {
    name: 'Chẩn',
    fullName: 'Chẩn Thủy Dẫn',
    animal: 'Giun đất',
    element: 'Thủy',
    weekday: 'Thứ Tư',
    direction: 'Nam Phương Chu Tước',
    isGood: true,
    rating: 'Đại Cát Tinh',
    poem: 'Chẩn tinh chiếu diệu đại hưng gia / Thăng quan tiến chức phúc đầy nhà / Cưới gả mua bán giai đắc lợi / Tử tôn hiếu thảo nở ngàn hoa.',
    goodFor: ['Cưới hỏi', 'Khai trương', 'Động thổ', 'Xuất hành', 'Cầu tài', 'Ký kết hợp đồng'],
    badFor: ['Chôn cất'],
  },
];

/**
 * Tính Sao trong Nhị Thập Bát Tú của ngày theo Julian Day Number
 * Công thức chuẩn xác: (jd + 11) % 28
 */
export function getDayNhiThapBatTu(jd) {
  const starIndex = (jd + 11) % 28;
  const star = NHI_THAP_BAT_TU[starIndex];
  return {
    starIndex,
    name: star.name,
    fullName: star.fullName,
    animal: star.animal,
    element: star.element,
    weekday: star.weekday,
    direction: star.direction,
    isGood: star.isGood,
    rating: star.rating,
    poem: star.poem,
    goodFor: star.goodFor,
    badFor: star.badFor,
  };
}
